version: '3.8'
services:
  db:
    image: postgres:17.2
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jwt_security
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
